-- ===========================================================================
-- Kami3D seed data — GENERATED FILE, DO NOT EDIT BY HAND.
--
-- Regenerate with:  npm run seed:generate
-- Source of truth:  data/animals.ts
--
-- Idempotent: re-running updates each species in place (matched on slug), so it is
-- safe to apply repeatedly and safe to run after editing the dataset.
-- ===========================================================================

insert into public.animals (
  id,
  slug,
  name,
  latin_name,
  category,
  habitat,
  region,
  conservation_status,
  diet,
  description,
  fun_facts,
  model_url,
  image_url,
  sound_url,
  scale_ratio,
  weight_kg,
  length_m,
  height_m,
  lifespan_years,
  is_prehistoric,
  premium,
  accent,
  emoji,
  silhouette,
  popularity
)
values
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000001', 'african-bush-elephant', 'African Bush Elephant', 'Loxodonta africana', 'Mammal', 'African savanna, bush & woodland', 'Africa', 'Endangered', 'Herbivore', 'The largest living land animal, the African bush elephant moves across the savanna in matriarch-led herds that share knowledge of waterholes across generations. Its dexterous trunk fuses the nose and upper lip, and its huge ears act as radiators that dump heat into the shade.', array['An elephant''s trunk contains roughly 40,000 muscles, far more than a human body has.', 'The ears can be flapped to shed heat and are shaped a little like the African continent.', 'Elephants dig for water with their tusks and trunk, creating pools other species rely on.', 'A calf can stand within an hour of birth and is protected by the whole herd.']::text[], '/models/african-bush-elephant.glb', null, null, 3.2, 6000, 6.5, 3.2, '60-70 years', false, false, array['#9aa3a8', '#3a3a3c']::text[], '🐘', 'quadruped', 96),
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000002', 'axolotl', 'Axolotl', 'Ambystoma mexicanum', 'Amphibian', 'Freshwater canals & lakes of Xochimilco, Mexico', 'North America', 'Critically Endangered', 'Carnivore', 'The axolotl is a salamander that never grows up: it keeps its feathery larval gills and stays aquatic for life. Once abundant in the canals of Xochimilco, wild numbers have collapsed as the waterways are drained, polluted and stocked with introduced fish.', array['It can regenerate whole limbs, its tail, and parts of its heart and brain without scarring.', 'Keeping juvenile features into adulthood is called neoteny, and the axolotl is its famous example.', 'Its name comes from Xolotl, the Aztec god associated with transformation and death.', 'Wild axolotls survive only in the Xochimilco canal system on the southern edge of Mexico City.']::text[], '/models/axolotl.glb', null, null, 0.25, 0.15, 0.25, 0.08, '10-15 years', false, false, array['#f2a0c0', '#2b1b2e']::text[], '🦎', 'quadruped', 90),
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000003', 'bald-eagle', 'Bald Eagle', 'Haliaeetus leucocephalus', 'Bird', 'Lakeshores, rivers & coasts of North America', 'North America', 'Least Concern', 'Piscivore', 'A sea eagle of North American waterways, the bald eagle snatches fish from the surface with talons that lock shut on contact. Its white head and tail only appear at about five years old, which is why the national bird is also called the white-headed eagle.', array['Wingspan can reach 2.3 metres, yet the skeleton weighs less than the bird''s feathers.', 'Its stick nests are among the largest built by any bird and are reused and enlarged for years.', 'The name comes from an old sense of bald meaning white-headed, not hairless.', 'A hunting eagle can stoop through the air at close to 160 km/h.']::text[], '/models/bald-eagle.glb', null, '/sounds/bald-eagle.mp3', 0.9, 5, 0.9, 0.7, '20-30 years', false, false, array['#f5f1e6', '#3b2a1a']::text[], '🦅', 'bird', 94),
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000004', 'bengal-tiger', 'Bengal Tiger', 'Panthera tigris', 'Mammal', 'Indian mangroves, grassland & dry forest', 'Asia', 'Endangered', 'Carnivore', 'The Bengal tiger is the classic striped big cat of the Indian subcontinent, hunting deer and wild boar alone across territories that can span a hundred square kilometres. In the Sundarbans it swims between mangrove islands, a rare skill among cats.', array['Every tiger''s stripe pattern is unique, and the skin beneath the fur is striped too.', 'A tiger''s roar can be heard about 3 km away in still forest air.', 'Tigers are strong swimmers and readily cross rivers and mangrove channels.', 'They are solitary ambush hunters that can drag prey heavier than themselves.']::text[], '/models/bengal-tiger.glb', null, null, 3.1, 220, 3.1, 1.1, '10-15 years', false, false, array['#e07b2a', '#1d1a17']::text[], '🐅', 'quadruped', 98),
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000005', 'blue-whale', 'Blue Whale', 'Balaenoptera musculus', 'Mammal', 'Open ocean, feeding in cold polar seas', 'Oceans', 'Endangered', 'Filter Feeder', 'The largest animal known to have lived, the blue whale sieves swarms of krill through baleen plates the size of fence slats. It feeds in cold, rich polar waters in summer and migrates thousands of kilometres toward the tropics to breed.', array['Its heart can weigh around 180 kg, about as much as a small car engine.', 'The tongue alone can weigh as much as an adult elephant.', 'A blue whale can eat up to four tonnes of krill in a single day.', 'Its low-frequency calls exceed 180 decibels and travel for hundreds of kilometres underwater.']::text[], '/models/blue-whale.glb', null, '/sounds/blue-whale.ogg', 27, 130000, 27, 4.5, '80-90 years', false, false, array['#3a6fb0', '#12233d']::text[], '🐋', 'whale', 97),
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000006', 'common-octopus', 'Common Octopus', 'Octopus vulgaris', 'Cephalopod', 'Coastal reefs, seagrass & rocky seabeds', 'Oceans', 'Data Deficient', 'Carnivore', 'A soft-bodied hunter with eight sucker-lined arms, the common octopus slips into rock crevices that no fish can follow. It changes colour and skin texture in a fraction of a second, vanishing into reef and rubble before a predator arrives.', array['It has three hearts and copper-based blood that is blue when oxygenated.', 'Chromatophore cells let it change colour and texture faster than a blink.', 'It swims by jet propulsion, expelling water through a steerable siphon.', 'A female guards her eggs without feeding and dies shortly after they hatch.']::text[], '/models/common-octopus.glb', null, null, 1, 3, 1, 0.3, '1-2 years', false, false, array['#d1665e', '#3a1f2b']::text[], '🐙', 'marine', 88),
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000007', 'emperor-penguin', 'Emperor Penguin', 'Aptenodytes forsteri', 'Bird', 'Antarctic sea ice & pack ice colonies', 'Antarctica', 'Endangered', 'Piscivore', 'The tallest penguin breeds on Antarctic sea ice in the middle of the polar winter, when temperatures drop below -50 degrees Celsius. Males balance a single egg on their feet under a brood pouch for two months while the females are away hunting at sea.', array['Emperor penguins have been recorded diving deeper than 500 metres.', 'Males fast for around two months while incubating, losing nearly half their body weight.', 'Thousands of birds huddle in tight groups that constantly shuffle so everyone takes a turn in the warm centre.', 'They cannot fly, but swim at about 6 km/h with short bursts almost twice that fast.']::text[], '/models/emperor-penguin.glb', null, null, 1.15, 30, 1, 1.15, '20 years', false, false, array['#f4c542', '#1b2733']::text[], '🐧', 'bird', 95),
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000008', 'giant-panda', 'Giant Panda', 'Ailuropoda melanoleuca', 'Mammal', 'Temperate bamboo forest of central China', 'Asia', 'Vulnerable', 'Herbivore', 'A bear that eats like a herbivore, the giant panda spends up to fourteen hours a day stripping bamboo, which its gut digests poorly. Its black-and-white coat and its enlarged wrist bone, which works as a thumb, suit a carnivore turned full-time browser.', array['A panda eats 12 to 38 kg of bamboo every day to stay fed.', 'An enlarged wrist bone works as a sixth thumb for gripping bamboo stems.', 'Newborn cubs weigh about 100 grams, roughly a thousandth of their mother''s weight.', 'Despite their bulk, pandas climb trees well and often nap in the branches.']::text[], '/models/giant-panda.glb', null, '/sounds/giant-panda.ogg', 1.6, 110, 1.6, 0.85, '20-30 years', false, false, array['#f2f2f0', '#1c1c1e']::text[], '🐼', 'quadruped', 95),
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000009', 'giraffe', 'Giraffe', 'Giraffa camelopardalis', 'Mammal', 'African savanna & open woodland', 'Africa', 'Vulnerable', 'Herbivore', 'The world''s tallest animal browses acacia crowns that no other herbivore can reach, using a prehensile 45-centimetre tongue to strip thorny leaves. Its long neck carries the same seven vertebrae as a human''s, each one enormously elongated.', array['A giraffe''s heart can weigh about 11 kg and pumps blood two metres up to the head.', 'The tongue is dark purple, which may protect it from sunburn while feeding.', 'No two giraffes share the same coat pattern, and each is stable for life.', 'Giraffes sleep very little, often in short bouts standing up.']::text[], '/models/giraffe.glb', null, null, 5.5, 1200, 4, 5.5, '20-25 years', false, false, array['#e0b25c', '#5a3a17']::text[], '🦒', 'quadruped', 92),
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000010', 'gooty-tarantula', 'Gooty Tarantula', 'Poecilotheria metallica', 'Arachnid', 'Dry deciduous forest of Andhra Pradesh, India', 'Asia', 'Critically Endangered', 'Insectivore', 'This arboreal tarantula is the only spider known to wear a metallic blue coat, patterned with a geometric mark on the abdomen. It lives in holes in old trees within a tiny forest fragment in southern India, and its entire known range is smaller than the city of Paris.', array['Its electric blue colour is unique among tarantulas and fades to grey as the spider ages.', 'The species was named after Gooty, the Indian town near where it was first collected.', 'It shelters by day in tree holes and is active at night, leaping between branches.', 'Its known range covers well under 100 square kilometres of degraded forest.']::text[], '/models/gooty-tarantula.glb', null, null, 0.2, 0.04, 0.2, 0.05, '10-15 years', false, false, array['#2f6fd0', '#f0c14b']::text[], '🕷️', 'insect', 62),
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000011', 'gray-wolf', 'Gray Wolf', 'Canis lupus', 'Mammal', 'Boreal forest, tundra & mountain ranges', 'Europe', 'Least Concern', 'Carnivore', 'The ancestor of every domestic dog, the gray wolf lives in family packs built around a breeding pair and their offspring. A single pack can patrol hundreds of square kilometres, shaping the movements of deer, elk and reindeer across the landscape.', array['A wolf pack is essentially a family, usually two parents and their young of several years.', 'A howl carries up to 10 km in open country and helps packs stay in contact.', 'Wolves routinely travel 30 km in a day and can cover far more when dispersing.', 'By culling weak prey, wolves keep herds healthier and reduce overgrazing.']::text[], '/models/gray-wolf.glb', null, '/sounds/gray-wolf.ogg', 1.5, 40, 1.5, 0.8, '6-8 years', false, false, array['#8d949c', '#2b3138']::text[], '🐺', 'quadruped', 89),
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000012', 'great-white-shark', 'Great White Shark', 'Carcharodon carcharias', 'Fish', 'Temperate & subtropical coastal seas', 'Oceans', 'Vulnerable', 'Carnivore', 'The great white is a torpedo-shaped lamnid shark that hunts seals and large fish in cool coastal waters, sometimes launching its whole body clear of the surface. Pores on its snout detect the faint electrical fields of a hidden fish, and it keeps its muscles warmer than the surrounding sea.', array['Ampullae of Lorenzini on its snout sense electrical fields produced by living prey.', 'It is one of the few fish that is partially warm-blooded, holding heat in its swimming muscles.', 'Females grow larger than males and can exceed 5 metres in length.', 'Attacks on surfboards from below often follow a full breach, with the shark leaving the water entirely.']::text[], '/models/great-white-shark.glb', null, null, 5, 1100, 5, 1.2, '70 years', false, false, array['#8fa3ad', '#22303a']::text[], '🦈', 'marine', 96),
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000013', 'green-anaconda', 'Green Anaconda', 'Eunectes murinus', 'Reptile', 'Amazon & Orinoco swamps and slow rivers', 'South America', 'Least Concern', 'Carnivore', 'The heaviest snake in the world, the green anaconda is an ambush hunter that waits in murky water with only its eyes and nostrils above the surface. It kills by constriction, coiling around prey such as caiman, capybara and deer before swallowing it whole.', array['Females are far larger than males and can weigh well over 100 kg.', 'Its eyes and nostrils sit on top of the head so it can breathe while almost fully submerged.', 'Unlike most snakes it gives birth to live young, sometimes dozens at once.', 'The name anaconda may derive from a Sinhalese word by way of Tamil, carried to South America by colonial-era writers.']::text[], '/models/green-anaconda.glb', null, null, 6, 70, 6, 0.3, '10-15 years', false, false, array['#4f8a3d', '#1f2a18']::text[], '🐍', 'serpent', 86),
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000014', 'king-cobra', 'King Cobra', 'Ophiophagus hannah', 'Reptile', 'South & Southeast Asian forest and plantation', 'Asia', 'Vulnerable', 'Carnivore', 'The longest venomous snake in the world, the king cobra specialises in eating other snakes, including cobras and pythons. Unusually for a snake, the female builds a nest of leaf litter and guards her eggs until they hatch.', array['It can exceed 5 metres in length, making it the longest venomous snake alive.', 'Its scientific name, Ophiophagus, means snake-eater.', 'It can rear up a third of its body and advance on an intruder while holding that pose.', 'The female stays with her nest for weeks, the closest thing to parental care among snakes.']::text[], '/models/king-cobra.glb', null, null, 4, 6, 4, 0.3, '20 years', false, false, array['#b9a24b', '#23301f']::text[], '🐍', 'serpent', 87),
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000015', 'lion', 'Lion', 'Panthera leo', 'Mammal', 'African savanna & grassland', 'Africa', 'Vulnerable', 'Carnivore', 'Lions are the only cats that live in permanent social groups, and a pride''s females do most of the hunting as a coordinated team. A male''s mane darkens with age and condition, advertising his fitness to rivals and mates alike.', array['A lion''s roar carries about 8 km across open savanna at night.', 'Pride females usually hunt together, fanning out to ambush herds from different sides.', 'Male lions can sleep for up to 20 hours a day between patrols.', 'Cubs are born with faint spots that fade as they grow.']::text[], '/models/lion.glb', null, '/sounds/lion.ogg', 2.5, 190, 2.5, 1.2, '10-14 years', false, false, array['#e8a33d', '#3d2410']::text[], '🦁', 'quadruped', 99),
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000016', 'megalodon', 'Megalodon', 'Otodus megalodon', 'Fish', 'Warm Miocene & Pliocene seas worldwide', 'Oceans', 'Extinct', 'Carnivore', 'Megalodon was a shark that grew longer than a city bus, hunting whales and other large marine mammals in warm seas for over thirteen million years. It is known mostly from its enormous fossil teeth, which are common enough to wash up on beaches today.', array['Its triangular teeth reached about 18 cm in slant height, among the largest of any fish.', 'Estimated bite forces exceed those calculated for Tyrannosaurus rex.', 'Nursery areas in shallow coastal water have been identified from fossil juvenile teeth.', 'It disappeared around 3.6 million years ago as oceans cooled and its prey shifted poleward.']::text[], '/models/megalodon.glb', null, null, 16, 50000, 16, 3.5, 'Unknown', true, true, array['#c8b48a', '#2b2118']::text[], '🦷', 'marine', 93),
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000017', 'monarch-butterfly', 'Monarch Butterfly', 'Danaus plexippus', 'Insect', 'Milkweed meadows & overwintering groves', 'North America', 'Endangered', 'Herbivore', 'Each autumn monarchs east of the Rockies stream up to 4,800 km to a handful of mountain forests in central Mexico, roosting in such dense clusters that branches bend under their weight. Caterpillars eat only milkweed, storing its toxins to make themselves poisonous to birds.', array['The orange wings warn predators of toxins absorbed from milkweed as a caterpillar.', 'No single butterfly makes the round trip: the return north takes three or four generations.', 'Overwintering colonies in Mexico can contain tens of millions of individuals.', 'A tagged monarch has been recorded flying nearly 4,800 km from Canada to Mexico.']::text[], '/models/monarch-butterfly.glb', null, null, 0.1, 0.0005, 0.1, 0.03, '2-6 weeks, 8-9 months for the migratory generation', false, false, array['#f08a1d', '#241a2e']::text[], '🦋', 'insect', 93),
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000018', 'red-kangaroo', 'Red Kangaroo', 'Osphranter rufus', 'Mammal', 'Australian arid outback & scrubland', 'Oceania', 'Least Concern', 'Herbivore', 'The largest living marsupial hops across the Australian interior on powerful hind legs, using its thick tail as a counterbalance and a fifth limb at slow speeds. Females can pause the development of an embryo until the previous joey leaves the pouch.', array['A red kangaroo can hop at around 60 km/h in short bursts.', 'A newborn joey is barely 2 cm long and crawls unaided into the pouch.', 'Males are rusty red while females are often blue-grey, once mistaken for a separate species.', 'Kangaroos cannot easily move backwards, which is why they appear on Australia''s coat of arms.']::text[], '/models/red-kangaroo.glb', null, null, 1.6, 85, 1.5, 1.6, '8-12 years', false, false, array['#c96a3a', '#4a2f1c']::text[], '🦘', 'biped', 91),
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000019', 'saltwater-crocodile', 'Saltwater Crocodile', 'Crocodylus porosus', 'Reptile', 'Mangroves, estuaries & coastal rivers', 'Oceania', 'Least Concern', 'Carnivore', 'The largest living reptile patrols mangroves and estuaries from eastern India to northern Australia, ambushing prey at the water''s edge with a bite measured as the strongest of any living animal. It tolerates salt water well enough to cross open ocean between islands.', array['Large males can exceed 6 metres and weigh over 1,000 kg.', 'Its bite has been measured as the most powerful of any living animal.', 'It can launch its body almost completely out of the water to seize prey above the surface.', 'Salt glands on the tongue let it survive for weeks in full-strength seawater.']::text[], '/models/saltwater-crocodile.glb', null, null, 5, 500, 5, 0.6, '60-70 years', false, false, array['#6f7f4a', '#2a2f1e']::text[], '🐊', 'quadruped', 84),
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000020', 'smilodon', 'Smilodon', 'Smilodon fatalis', 'Mammal', 'Pleistocene grassland & woodland of the Americas', 'North America', 'Extinct', 'Carnivore', 'Smilodon, the saber-toothed cat, ambushed large Pleistocene herbivores with canine teeth nearly 30 cm long. Its stocky body and powerful forelimbs were built for wrestling prey to the ground rather than for long chases.', array['Its upper canines could reach about 28 cm, including the root.', 'Smilodon had unusually robust forelimbs, useful for pinning struggling prey.', 'Thousands of Smilodon fatalis fossils have been recovered from the La Brea Tar Pits in Los Angeles.', 'It died out roughly 10,000 years ago, along with much of the Pleistocene megafauna.']::text[], '/models/smilodon.glb', null, null, 1.2, 280, 2.1, 1.2, 'Unknown', true, true, array['#c9a06a', '#43301f']::text[], '🦴', 'quadruped', 82),
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000021', 'toco-toucan', 'Toco Toucan', 'Ramphastos toco', 'Bird', 'South American savanna, forest edge & palm groves', 'South America', 'Least Concern', 'Omnivore', 'The toco toucan carries the largest bill of any toucan, a hollow 20-centimetre structure that looks heavy but weighs less than its feathers. It plucks fruit at the end of thin branches and tosses each item into the air before catching and swallowing it.', array['Its bill is mostly air-filled keratin, so it is far lighter than it looks.', 'Blood vessels in the bill shed heat, making it an important radiator in the tropics.', 'It sleeps with the bill resting along its back and the tail folded over it.', 'Toucans nest in tree cavities and are important seed dispersers in the Cerrado and Amazon.']::text[], '/models/toco-toucan.glb', null, '/sounds/toco-toucan.ogg', 0.6, 0.7, 0.6, 0.35, '20 years', false, false, array['#f26b21', '#1b1b1f']::text[], '🦜', 'bird', 85),
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000022', 'tyrannosaurus-rex', 'Tyrannosaurus rex', 'Tyrannosaurus rex', 'Reptile', 'Late Cretaceous floodplains & forests', 'North America', 'Extinct', 'Carnivore', 'Tyrannosaurus rex was a 12-metre predator of the Late Cretaceous, with a skull built to deliver one of the most powerful bites of any land animal. Its arms were famously short, yet each was strong enough to hold struggling prey close.', array['Its bite force is estimated among the highest of any land animal that has ever lived.', 'Around 60 teeth lined its jaws, some over 30 cm long including the root.', 'Its arms were short but heavily muscled, with two clawed fingers on each hand.', 'It lived between about 68 and 66 million years ago, at the very end of the dinosaur era.']::text[], '/models/tyrannosaurus-rex.glb', null, null, 12.3, 8000, 12.3, 4, 'Unknown', true, true, array['#6b8f3e', '#2a2418']::text[], '🦖', 'theropod', 97),
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000023', 'weddell-seal', 'Weddell Seal', 'Leptonychotes weddellii', 'Mammal', 'Fast ice & coastal waters around Antarctica', 'Antarctica', 'Least Concern', 'Piscivore', 'The Weddell seal lives further south than any other mammal, hauling out on the fast ice around Antarctica and slipping into the water through holes it keeps open with its teeth. It dives deeper and longer than almost any other seal, hunting fish beneath metres of ice.', array['It can dive deeper than 600 metres and stay submerged for over an hour.', 'Seals rasp their breathing holes open with their teeth, which wear down over a lifetime.', 'Weddell seals are the most southerly breeding mammal on Earth.', 'Pups are born on the ice in spring and can swim within days.']::text[], '/models/weddell-seal.glb', null, null, 3, 450, 3, 0.6, '20-25 years', false, false, array['#a8b6bd', '#33414d']::text[], '🦭', 'marine', 76),
  ('7c9e6b1a-1f2d-4a3b-8c4d-000000000024', 'woolly-mammoth', 'Woolly Mammoth', 'Mammuthus primigenius', 'Mammal', 'Ice Age mammoth steppe of Eurasia', 'Europe', 'Extinct', 'Herbivore', 'The woolly mammoth roamed the cold grasslands of Ice Age Eurasia, wrapped in a dense coat of guard hairs and wool with a layer of fat beneath. Curved tusks up to four metres long were used to sweep snow aside in search of frozen grass.', array['Its tusks could grow to about 4 metres and are among the largest of any elephant relative.', 'Small ears and a short tail limited heat loss in the freezing steppe climate.', 'Whole carcasses with skin and hair intact have been recovered from Siberian permafrost.', 'A dwarfed population survived on Wrangel Island until roughly 4,000 years ago.']::text[], '/models/woolly-mammoth.glb', null, null, 3.4, 6000, 5, 3.4, '60-80 years', true, true, array['#a9744f', '#4a3524']::text[], '🦣', 'quadruped', 88)
on conflict (slug) do update set
  name = excluded.name,
  latin_name = excluded.latin_name,
  category = excluded.category,
  habitat = excluded.habitat,
  region = excluded.region,
  conservation_status = excluded.conservation_status,
  diet = excluded.diet,
  description = excluded.description,
  fun_facts = excluded.fun_facts,
  model_url = excluded.model_url,
  image_url = excluded.image_url,
  sound_url = excluded.sound_url,
  scale_ratio = excluded.scale_ratio,
  weight_kg = excluded.weight_kg,
  length_m = excluded.length_m,
  height_m = excluded.height_m,
  lifespan_years = excluded.lifespan_years,
  is_prehistoric = excluded.is_prehistoric,
  premium = excluded.premium,
  accent = excluded.accent,
  emoji = excluded.emoji,
  silhouette = excluded.silhouette,
  popularity = excluded.popularity;

-- Sanity check: should report 24.
-- select count(*) as seeded_species from public.animals;

-- Sanity check: species per region.
-- select region, count(*) from public.animals group by region order by region;
