/**
 * Interface tones, synthesised rather than downloaded.
 *
 * The audio settings needed something honest to control: the quiz is the one place
 * where a sound tells the visitor something the screen already says, and shipping a
 * few hundred kilobytes of MP3 for two blips would cost more than the feature is
 * worth. So a correct answer is a short rising pair of sine tones and a wrong one a
 * single lower tone, generated by the Web Audio API — no file, no request, and the
 * gain is the visitor's own master × interface volume.
 *
 * Nothing here throws. A browser that has not seen a user gesture, an ancient
 * WebKit without `AudioContext`, or a visitor at 0% volume all end up in the same
 * place: silence, and a quiz that still works.
 */

export type ToneKind = "correct" | "wrong" | "click";

interface Tone {
  /** Frequencies played in order, in Hz. */
  notes: number[];
  duration: number;
  type: OscillatorType;
}

const TONES: Record<ToneKind, Tone> = {
  correct: { notes: [660, 990], duration: 0.12, type: "sine" },
  wrong: { notes: [220], duration: 0.22, type: "triangle" },
  click: { notes: [440], duration: 0.05, type: "sine" },
};

let context: AudioContext | null = null;

function audioContext(): AudioContext | null {
  if (context) return context;
  const Ctor = globalThis.AudioContext ?? (globalThis as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
  if (!Ctor) return null;
  try {
    context = new Ctor();
    return context;
  } catch {
    return null;
  }
}

/**
 * Plays one tone at the given gain (0–1). Silent, and safe, when gain is 0 or the
 * browser cannot make sound at all.
 */
export function playTone(kind: ToneKind, gain: number): void {
  if (gain <= 0) return;
  const audio = audioContext();
  if (!audio) return;

  const tone = TONES[kind];
  // A context created before any gesture starts "suspended"; resuming inside a
  // click handler is allowed, and failing to resume just means no sound.
  if (audio.state === "suspended") void audio.resume().catch(() => undefined);

  const start = audio.currentTime;
  tone.notes.forEach((frequency, index) => {
    const at = start + index * tone.duration;
    const oscillator = audio.createOscillator();
    const volume = audio.createGain();

    oscillator.type = tone.type;
    oscillator.frequency.setValueAtTime(frequency, at);
    // A short fade at each end: a raw square edge on gain is an audible click.
    volume.gain.setValueAtTime(0, at);
    volume.gain.linearRampToValueAtTime(gain, at + 0.01);
    volume.gain.linearRampToValueAtTime(0, at + tone.duration);

    oscillator.connect(volume).connect(audio.destination);
    oscillator.start(at);
    oscillator.stop(at + tone.duration + 0.02);
  });
}
