#!/usr/bin/env node
/**
 * Generates the bundled geospatial sample: `data/animal-geodata.json`.
 *
 *   node scripts/generate-geodata.mjs           # write the files
 *   node scripts/generate-geodata.mjs --check   # fail if they are out of date (CI)
 *
 * ## What this data is, and what it is not
 *
 * It is **synthetic**, and it says so in every feature: a deterministic envelope around
 * the species' regional anchor, labelled "demo envelope" with `"synthetic": true` and a
 * `note` the UI is expected to show. It is not a published range map.
 *
 * The alternative was to ship nothing and make `/map` depend entirely on Supabase, which
 * would leave a fresh clone - Demo Mode, no environment variables - with a blank page.
 * The project rule is the same one `data/animals.ts` follows: the bundled dataset is the
 * source of truth, the database is a copy of it.
 *
 * Real ranges are a licensing question before they are a data question: IUCN range maps
 * restrict commercial use, and GBIF records are CC BY 4.0 and must be cited with the DOI
 * of the download. Those arrive through `scripts/fetch-geodata.mjs`, which records the
 * licence and attribution per row - and until then this file is what the map draws.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { ANIMALS } from "../data/animals.ts";
import { envelopeRing, ringAreaKm2, ringIsClosed, ringIsSimple } from "../lib/geo.ts";
import { REGION_ANCHORS } from "../types/animal.ts";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DATA_DIR = join(ROOT, "data");
// `.json`, not `.geojson`: the app imports it as a module, and a bundler that knows
// JSON does not necessarily know `.geojson`. The content is still a FeatureCollection.
const GEOJSON_FILE = join(DATA_DIR, "animal-geodata.json");
const ATTRIBUTION_FILE = join(DATA_DIR, "geodata-attribution.json");

const SOURCE = "kami3d-demo-envelope";

/** A stable number from a slug, so a species keeps the same envelope forever. */
function seedFrom(slug) {
  let hash = 2166136261;
  for (let i = 0; i < slug.length; i += 1) {
    hash ^= slug.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return Math.abs(hash % 1000);
}

/** 220-560 km: a blip on a world map, deliberately too small to be mistaken for a range. */
function radiusFor(slug) {
  return 220 + (seedFrom(slug) % 340);
}

function feature(animal, region, kind, year, radiusKm) {
  const anchor = REGION_ANCHORS[region];
  // 18 vertices: enough that the envelope reads as an area rather than a polygon, and
  // small enough that the whole bundled file stays around 20 KB in the repository and
  // in the map route payload.
  const ring = envelopeRing({ lat: anchor.lat, lng: anchor.lng }, {
    radiusKm,
    points: 18,
    seed: seedFrom(animal.slug) + (year ?? 0),
  });

  if (!ringIsClosed(ring) || !ringIsSimple(ring)) {
    throw new Error(`generated an invalid ring for ${animal.slug} (${kind}) - refusing to write it`);
  }

  return {
    type: "Feature",
    properties: {
      slug: animal.slug,
      name: animal.name,
      latin_name: animal.latin_name,
      region,
      category: animal.category,
      conservation_status: animal.conservation_status,
      kind,
      year,
      source: SOURCE,
      license: "CC0",
      synthetic: true,
      radius_km: radiusKm,
      area_km2: Math.round(ringAreaKm2(ring)),
      note:
        "Demo envelope: a synthetic area around this species' regional anchor, not a published range map.",
    },
    geometry: { type: "Polygon", coordinates: [ring] },
  };
}

export function buildGeodata() {
  const features = [];

  for (const animal of ANIMALS) {
    const radiusKm = radiusFor(animal.slug);
    features.push(feature(animal, animal.region, "habitat_current", null, radiusKm));

    // A prehistoric species also has a historic range, which is the row Phase 15 and 16
    // need and the reason `year` exists from the first migration rather than the fourth.
    if (animal.is_prehistoric) {
      features.push(feature(animal, animal.region, "habitat_historic", -10000, Math.round(radiusKm * 1.6)));
    }
  }

  const collection = {
    type: "FeatureCollection",
    // Sorted by slug then kind, so regenerating the file is a no-op in git.
    features: features.sort((a, b) =>
      a.properties.slug.localeCompare(b.properties.slug) ||
      String(a.properties.kind).localeCompare(String(b.properties.kind)),
    ),
  };

  const attribution = {
    [SOURCE]: {
      label: "Kami3D demo envelopes",
      license: "CC0-1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      attribution: "Synthetic envelopes generated by Kami3D from regional anchors.",
      note: "Not a published range map. Replace with GBIF/IUCN data through scripts/fetch-geodata.mjs.",
    },
  };

  return { collection, attribution };
}

const check = process.argv.includes("--check");
const { collection, attribution } = buildGeodata();
// Minified on purpose: this file is generated, committed and checked into a client
// payload - indentation here buys nobody anything.
const geojson = `${JSON.stringify(collection)}\n`;
const credits = `${JSON.stringify(attribution, null, 2)}\n`;

if (check) {
  const current = (file) => {
    try {
      return readFileSync(file, "utf8");
    } catch {
      return null;
    }
  };

  const stale = [
    current(GEOJSON_FILE) !== geojson ? "data/animal-geodata.json" : null,
    current(ATTRIBUTION_FILE) !== credits ? "data/geodata-attribution.json" : null,
  ].filter(Boolean);

  if (stale.length > 0) {
    console.error(`Geodata is out of date: ${stale.join(", ")}`);
    console.error("Run: npm run geodata:generate");
    process.exit(1);
  }

  console.log(`Geodata is up to date (${collection.features.length} features).`);
} else {
  writeFileSync(GEOJSON_FILE, geojson, "utf8");
  writeFileSync(ATTRIBUTION_FILE, credits, "utf8");
  const area = collection.features.reduce((sum, f) => sum + f.properties.area_km2, 0);
  console.log(`Wrote ${collection.features.length} features to data/animal-geodata.json`);
  console.log(`  ${new Set(collection.features.map((f) => f.properties.slug)).size} species, ${area.toLocaleString("en-US")} km2 total`);
}
