#!/usr/bin/env node
/**
 * Generate a 3D model for a species with Meshy, and record where it came from.
 *
 *   node scripts/generate-models.mjs --list                       # who needs one, and what it costs
 *   node scripts/generate-models.mjs --species=walrus,reindeer    # dry run
 *   node scripts/generate-models.mjs --species=walrus --apply     # generate, download, credit, wire
 *
 * ## The licence, which is the whole reason this file has a long header
 *
 * Meshy's own pricing table is the source: the **Free plan licenses its output CC BY 4.0**
 * (attribution required, commercial use allowed), while the paid plans hand the output over privately
 * under no standard licence. `lib/model-quality.ts` allows CC0 and CC BY and nothing else, so this
 * script is written for the free plan and hard-codes `CC-BY-4.0` rather than taking it as a flag -
 * a flag is how a paid key would quietly record a licence it does not have.
 *
 * ## What a generated model is, said plainly
 *
 * Meshy is a text-to-3D generator, not a library of scans. The model it returns is a **plausible
 * reconstruction from the words it was given**, not a photographed or scanned specimen. That is why
 * every entry this script writes carries a `generated` record and the species page prints
 * "generated by Meshy from a text description — a reconstruction, not a scan of a real animal". A
 * synthesised animal presented as a real one would be the same failure this project refuses
 * everywhere else; it is honest as an illustration and dishonest as a specimen.
 *
 * ## Credits
 *
 * The free plan is 100 credits a month. Text to 3D is a two-step task - a preview (geometry) and a
 * refine (texture) - and both are billed: 20 + 10 credits on meshy-7.1, so **about three models a
 * month**. `--max-credits` defaults to the monthly allowance and stops the run before it spends
 * anything the account does not have; a failed generation is not billed, so a retry is free.
 */

import { createHash } from "node:crypto";
import { existsSync, readdirSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { setTimeout as sleep } from "node:timers/promises";

import { ANIMALS } from "../data/animals.ts";
import { compressGlb } from "./fetch-models.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const API = "https://api.meshy.ai/openapi/v2/text-to-3d";
const MODEL = process.env.MESHY_MODEL ?? "meshy-7.1";

/** The licence the Free plan grants. Not a parameter: a paid key does not grant it. */
const LICENSE = "CC-BY-4.0";
const LICENSE_URL = "https://creativecommons.org/licenses/by/4.0/";
const PROVIDER = "meshy";
const AUTHOR = "Meshy AI";
const AUTHOR_URL = "https://www.meshy.ai";

/** Credits per step, from Meshy's published API pricing for meshy-7.1. */
const CREDITS = { preview: 20, refine: 10 };

const flags = process.argv.slice(2);
const APPLY = flags.includes("--apply");
const LIST = flags.includes("--list");
const value = (name, fallback) => {
  const hit = flags.find((arg) => arg.startsWith("--" + name + "="));
  return hit ? hit.slice(name.length + 3) : fallback;
};
const requested = (value("species", "") ?? "").split(",").map((slug) => slug.trim()).filter(Boolean);
const maxCredits = Number(value("max-credits", String(CREDITS.preview + CREDITS.refine)));
const maxModels = Number(value("max", "99"));

/* ------------------------------------------------------------------ the key */

async function loadEnv() {
  for (const name of [".env.local", ".env"]) {
    const path = join(ROOT, name);
    if (!existsSync(path)) continue;
    for (const line of (await readFile(path, "utf8")).split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#") || !trimmed.includes("=")) continue;
      const separator = trimmed.indexOf("=");
      const key = trimmed.slice(0, separator).trim();
      if (!process.env[key]) process.env[key] = trimmed.slice(separator + 1).trim().replace(/^["']|["']$/g, "");
    }
  }
}
await loadEnv();

const apiKey = (process.env.MESHY_API_KEY ?? "").trim();
const auth = { authorization: "Bearer " + apiKey, "content-type": "application/json" };

/* ------------------------------------------------------------------ who needs one */

const attributionFile = join(ROOT, "data", "model-attribution.json");
const previewFile = join(ROOT, "data", "model-preview.json");
const attribution = JSON.parse(await readFile(attributionFile, "utf8"));

const candidates = ANIMALS.filter((animal) => !animal.model_url);

if (LIST || requested.length === 0) {
  console.log(candidates.length + " species in the catalogue have no model:");
  for (const animal of candidates) {
    console.log("  " + animal.slug.padEnd(28) + animal.name.padEnd(26) + animal.region);
  }
  const perModel = CREDITS.preview + CREDITS.refine;
  console.log("\n" + perModel + " credits each on " + MODEL + " (preview " + CREDITS.preview + " + refine " + CREDITS.refine + ").");
  console.log("The free plan is 100 credits a month, so about " + Math.floor(100 / perModel) + " models a month.");
  console.log("\nPick some: --species=" + candidates.slice(0, 3).map((animal) => animal.slug).join(","));
  process.exit(0);
}

const chosen = [];
for (const slug of requested) {
  const animal = ANIMALS.find((entry) => entry.slug === slug);
  if (!animal) {
    console.error("  ! " + slug + " is not in the catalogue. Restore it first:");
    console.error("      node scripts/restore-species.mjs --species=" + slug + " --apply");
    continue;
  }
  if (animal.model_url) {
    console.log("  = " + slug + " already has a model (" + animal.model_url + ")");
    continue;
  }
  chosen.push(animal);
}

const perModel = CREDITS.preview + CREDITS.refine;
const affordable = Math.min(maxModels, Math.floor(maxCredits / perModel), chosen.length);

console.log("\n" + chosen.length + " requested, " + affordable + " within a " + maxCredits + "-credit budget:");
for (const animal of chosen.slice(0, affordable)) console.log("  + " + animal.slug.padEnd(28) + animal.name);

if (affordable === 0) {
  console.log("\nNothing to do inside the budget. Raise --max-credits if the account has more.");
  process.exit(0);
}

if (!apiKey) {
  console.error("\nMESHY_API_KEY is not set. Put it in .env.local (it is gitignored) and run again:");
  console.error("  MESHY_API_KEY=msy_...     # https://www.meshy.ai/api");
  process.exit(2);
}

if (!APPLY) {
  console.log("\nDry run. Add --apply to generate. It will spend up to " + affordable * perModel + " credits.");
  process.exit(0);
}

/* ------------------------------------------------------------------ the API */

async function call(path, init) {
  const response = await fetch(API + path, { ...init, headers: { ...auth, ...(init?.headers ?? {}) } });
  const text = await response.text();
  if (!response.ok) {
    throw new Error("Meshy answered " + response.status + ": " + text.slice(0, 300));
  }
  return text ? JSON.parse(text) : {};
}

/**
 * A prompt that asks for the animal and nothing else.
 *
 * Text-to-3D follows the object more closely when the prompt is a description of one thing rather
 * than a paragraph about it, so this is the species, its Latin name, and the two things a viewer
 * needs to read the shape: a whole body in a neutral pose, and no scene around it.
 */
function promptFor(animal) {
  return [
    "A single " + animal.name + " (" + animal.latin_name + ")",
    "full body, complete animal, neutral standing pose",
    "accurate anatomy, realistic proportions",
    "wildlife documentary style, photorealistic",
    "plain untextured studio background, no props, no base",
  ].join(". ");
}

async function waitFor(taskId, label) {
  const deadline = Date.now() + 15 * 60_000;
  let last = "";
  while (Date.now() < deadline) {
    const task = await call("/" + taskId, { method: "GET" });
    const status = String(task.status ?? "?");
    if (status !== last) {
      console.log("      " + label + ": " + status + (task.progress ? " " + task.progress + "%" : ""));
      last = status;
    }
    if (status === "SUCCEEDED") return task;
    if (status === "FAILED" || status === "CANCELED" || status === "EXPIRED") {
      throw new Error(label + " " + status + ": " + (task.task_error?.message ?? "no reason given"));
    }
    await sleep(5000);
  }
  throw new Error(label + " did not finish in fifteen minutes; the task id is " + taskId);
}

/* ------------------------------------------------------------------ generate */

const written = [];

for (const animal of chosen.slice(0, affordable)) {
  console.log("\n" + animal.slug + " — " + animal.name);
  const prompt = promptFor(animal);
  console.log("    prompt: " + prompt.slice(0, 120) + (prompt.length > 120 ? "…" : ""));

  try {
    const previewId = (await call("", {
      method: "POST",
      body: JSON.stringify({ mode: "preview", prompt, ai_model: MODEL, art_style: "realistic", should_remesh: true }),
    })).result;
    console.log("    preview " + previewId);
    await waitFor(previewId, "preview");

    const refineId = (await call("", {
      method: "POST",
      body: JSON.stringify({ mode: "refine", preview_task_id: previewId }),
    })).result;
    console.log("    refine  " + refineId);
    const refined = await waitFor(refineId, "refine");

    const url = refined.model_urls?.glb;
    if (!url) throw new Error("no glb in the finished task");

    const response = await fetch(url);
    if (!response.ok) throw new Error("the model download answered " + response.status);
    const buffer = Buffer.from(await response.arrayBuffer());

    const target = join(ROOT, "public", "models", animal.slug + ".glb");
    await writeFile(target, buffer);
    console.log("    downloaded " + (buffer.length / 1048576).toFixed(1) + " MB");

    const compressed = await compressGlb(target);
    if (compressed.kept) {
      console.log("    DRACO " + (compressed.before / 1048576).toFixed(1) + " MB → " + (compressed.after / 1048576).toFixed(1) + " MB");
    }

    const final = await readFile(target);
    written.push({
      slug: animal.slug,
      entry: {
        // The title is the species name because that is what was asked for. It is what
        // `npm run models:audit` scores and what `scripts/wire-local-models.mjs` gates on.
        title: animal.name,
        author: AUTHOR,
        authorUrl: AUTHOR_URL,
        license: LICENSE,
        licenseUrl: LICENSE_URL,
        sourceUrl: "https://www.meshy.ai/",
        provider: PROVIDER,
        file: "/models/" + animal.slug + ".glb",
        format: "glb",
        bytes: final.length,
        sha256: createHash("sha256").update(final).digest("hex"),
        attributionRequired: true,
        fetchedAt: new Date().toISOString(),
        faceCount: null,
        generated: { provider: PROVIDER, model: MODEL, prompt, taskId: previewId, at: new Date().toISOString() },
      },
    });
  } catch (error) {
    console.error("    FAILED: " + String(error.message).split("\n")[0]);
    console.error("    a failed generation is not billed, so this one can simply be retried");
  }
}

if (written.length === 0) {
  console.log("\nNothing was written.");
  process.exit(1);
}

for (const row of written) attribution[row.slug] = row.entry;
const sorted = Object.fromEntries(Object.entries(attribution).sort(([a], [b]) => a.localeCompare(b)));
await writeFile(attributionFile, JSON.stringify(sorted, null, 2) + "\n", "utf8");

// The same derived index scripts/fetch-models.mjs writes, in the same shape, so a card reads the
// size and triangle count from one place whoever produced the model.
await writeFile(
  previewFile,
  JSON.stringify({
    note: "Generated by scripts/fetch-models.mjs from data/model-attribution.json. Compact on purpose: a species card imports this on hover, so it carries only the size and triangle count the preview budget needs. Edit the manifest, not this file; check:preview fails if they disagree.",
    models: Object.fromEntries(Object.entries(sorted).map(([slug, entry]) => [slug, [entry.bytes ?? 0, entry.faceCount ?? null]])),
  }) + "\n",
  "utf8",
);

console.log("\nWrote " + written.length + " model(s) and their credits. Now wire them:");
console.log("  node scripts/wire-local-models.mjs --apply");
console.log("  npm run geo:generate && npm run seed:generate && npm run db:seed");
